version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://monty:monty@postgres:5432/monty?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: monty
      POSTGRES_PASSWORD: monty
      POSTGRES_DB: monty
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
